### ISSUE TITLE
Fresh install fails tests (but just for me?)

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-server#25]
Since this morning, tests will not run for me. I've tried fresh installs, but am not getting to the root of it. I had it running under Conda yesterday, but that failed this morning, so I tried running with the default python, hit the same problem. Now I have what I think is an entirely fresh conda install, and am still hitting these issues.
```
(python2) higlass-server$ which python
/Users/chuck/anaconda3/envs/python2/bin/python
(python2) higlass-server$ python --version
Python 2.7.13 :: Continuum Analytics, Inc.
```
Other tests also fail, but all the stack traces end the same way:
```
ERROR: test_get_info (tilesets.tests.GetterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/github/hms-dbmi/higlass-server/tilesets/tests.py", line 296, in test_get_info
    info = cch.get_info(filepath)
  File "/Users/chuck/github/hms-dbmi/higlass-server/src/cooler/cooler/contrib/higlass.py", line 163, in get_info
    with h5py.File(file_path, 'r') as f:
  File "/Users/chuck/anaconda3/envs/python2/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/Users/chuck/anaconda3/envs/python2/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2687)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/_objects.c:2645)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/Users/travis/build/MacPython/h5py-wheels/h5py/h5py/h5f.c:1933)
IOError: Unable to open file (File signature not found)
```

`/Users/travis` is really weird.

**Comment by mccalluc** [comment]
This is still odd, but I am able to get work done working inside docker.
