### ISSUE TITLE
Unit tests in readme.md failing

### ISSUE THREAD

**Issue by mccalluc** [hms-dbmi/higlass-server#4]
I think it's just more wgets needed in the readme... perhaps move this setup inside the test, and have it run on Travis.

```
======================================================================
ERROR: test_get_tile (tilesets.tests.BedDBTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/github/hms-dbmi/higlass-server/tilesets/tests.py", line 97, in setUp
    upload_file = open('data/gene_annotations.short.db', 'r')
IOError: [Errno 2] No such file or directory: 'data/gene_annotations.short.db'

======================================================================
ERROR: test_upload_file (tilesets.tests.FileUploadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/github/hms-dbmi/higlass-server/tilesets/tests.py", line 60, in test_upload_file
    f = open( 'data/tiny.txt', 'r')
IOError: [Errno 2] No such file or directory: 'data/tiny.txt'

======================================================================
ERROR: test_hibed_get_tile (tilesets.tests.HiBedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/github/hms-dbmi/higlass-server/tilesets/tests.py", line 122, in setUp
    upload_file = open('data/cnv_short.hibed', 'r')
IOError: [Errno 2] No such file or directory: 'data/cnv_short.hibed'

======================================================================
ERROR: test_hibed_get_tileset_info (tilesets.tests.HiBedTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/github/hms-dbmi/higlass-server/tilesets/tests.py", line 122, in setUp
    upload_file = open('data/cnv_short.hibed', 'r')
IOError: [Errno 2] No such file or directory: 'data/cnv_short.hibed'

======================================================================
ERROR: test_suggest (tilesets.tests.SuggestionsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chuck/github/hms-dbmi/higlass-server/tilesets/tests.py", line 28, in setUp
    upload_file = open('data/gene_annotations.short.db', 'r')
IOError: [Errno 2] No such file or directory: 'data/gene_annotations.short.db'

----------------------------------------------------------------------
Ran 20 tests in 11.035s
```

**Comment by mccalluc** [comment]
That section of the README is gone.
